"""add_ai_summary_to_articles

Revision ID: 90438340927e
Revises: 
Create Date: 2026-06-19 13:11:47.105343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90438340927e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('summary_bullet', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('summary_journalistic', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('summary_simple', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'summary_simple')
    op.drop_column('articles', 'summary_journalistic')
    op.drop_column('articles', 'summary_bullet')
    # ### end Alembic commands ###
