"""add_reading_time_and_content_type

Revision ID: d82515c41072
Revises: eacd03e22f1e
Create Date: 2026-06-25 06:45:37.303969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82515c41072'
down_revision: Union[str, None] = 'eacd03e22f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('reading_time', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'content_type')
    op.drop_column('articles', 'reading_time')
    # ### end Alembic commands ###
